import { Organization, Workspace, Pauta, CalendarEvent, BrandDNA } from '@/types'

export const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === 'true'

export const demoOrg: Organization = {
  id: 'demo-org-1',
  name: 'Nexum360',
  slug: 'nexum360',
  logo_url: null,
  plan: 'pro',
  stripe_customer_id: null,
  stripe_subscription_id: null,
  stripe_subscription_status: 'active',
  trial_ends_at: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const demoWorkspaces: Workspace[] = [
  {
    id: 'demo-ws-1',
    organization_id: 'demo-org-1',
    name: 'Nexum360',
    slug: 'nexum360',
    description: 'Workspace principal',
    color: '#6366f1',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-ws-2',
    organization_id: 'demo-org-1',
    name: 'Cliente A',
    slug: 'cliente-a',
    description: 'Workspace do Cliente A',
    color: '#10b981',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const demoPautas: Pauta[] = [
  {
    id: 'p1',
    workspace_id: 'demo-ws-1',
    title: '5 tendências de IA que vão transformar o marketing em 2025',
    description: 'Abordagem educativa mostrando as principais tendências de IA aplicadas ao marketing digital.',
    category: 'Educacional',
    platform: ['linkedin', 'instagram'],
    format: 'carrossel',
    status: 'aprovado',
    tags: ['ia', 'marketing', 'tendencias'],
    priority: 'alta',
    scheduled_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    published_at: null,
    created_by: null,
    assigned_to: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p2',
    workspace_id: 'demo-ws-1',
    title: 'Case: Como a empresa X triplicou seus leads com conteúdo estratégico',
    description: 'Storytelling do case de sucesso com dados reais e metodologia aplicada.',
    category: 'Cases',
    platform: ['linkedin'],
    format: 'artigo',
    status: 'em_desenvolvimento',
    tags: ['case', 'leads', 'estrategia'],
    priority: 'media',
    scheduled_date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    published_at: null,
    created_by: null,
    assigned_to: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p3',
    workspace_id: 'demo-ws-1',
    title: 'Por que sua marca precisa de uma estratégia de conteúdo antes de postar',
    description: 'Post provocativo que gera reflexão e posiciona a marca como especialista.',
    category: 'Marketing',
    platform: ['instagram', 'facebook'],
    format: 'post',
    status: 'ideia',
    tags: ['estrategia', 'branding', 'conteudo'],
    priority: 'baixa',
    scheduled_date: null,
    published_at: null,
    created_by: null,
    assigned_to: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p4',
    workspace_id: 'demo-ws-1',
    title: 'Bastidores: como montamos nossa estratégia de conteúdo para Q2',
    description: 'Conteúdo de bastidores mostrando o processo interno da agência.',
    category: 'Bastidores',
    platform: ['instagram'],
    format: 'reels',
    status: 'aprovado',
    tags: ['bastidores', 'processo', 'agencia'],
    priority: 'media',
    scheduled_date: new Date(Date.now() + 1 * 86400000).toISOString().split('T')[0],
    published_at: null,
    created_by: null,
    assigned_to: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p5',
    workspace_id: 'demo-ws-1',
    title: 'Newsletter: As 3 notícias de marketing digital que você não pode ignorar',
    description: 'Curadoria semanal das principais novidades do mercado.',
    category: 'Tendências',
    platform: ['newsletter'],
    format: 'newsletter',
    status: 'publicado',
    tags: ['newsletter', 'noticias', 'marketing'],
    priority: 'alta',
    scheduled_date: null,
    published_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    created_by: null,
    assigned_to: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p6',
    workspace_id: 'demo-ws-1',
    title: 'Thread: O guia completo de copywriting para redes sociais',
    description: '10 tweets com técnicas práticas de copywriting aplicadas ao social media.',
    category: 'Educacional',
    platform: ['twitter'],
    format: 'thread',
    status: 'ideia',
    tags: ['copywriting', 'twitter', 'guia'],
    priority: 'baixa',
    scheduled_date: null,
    published_at: null,
    created_by: null,
    assigned_to: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: 'e1',
    workspace_id: 'demo-ws-1',
    pauta_id: 'p4',
    title: 'Reels - Bastidores Q2',
    description: null,
    platform: ['instagram'],
    scheduled_date: new Date(Date.now() + 1 * 86400000).toISOString().split('T')[0],
    scheduled_time: '09:00',
    status: 'agendado',
    color: '#6366f1',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'e2',
    workspace_id: 'demo-ws-1',
    pauta_id: 'p1',
    title: 'Carrossel - Tendências IA',
    description: null,
    platform: ['linkedin', 'instagram'],
    scheduled_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    scheduled_time: '11:00',
    status: 'agendado',
    color: '#10b981',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'e3',
    workspace_id: 'demo-ws-1',
    pauta_id: 'p2',
    title: 'Artigo LinkedIn - Case X',
    description: null,
    platform: ['linkedin'],
    scheduled_date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    scheduled_time: '14:00',
    status: 'agendado',
    color: '#f59e0b',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const demoBrandDna: BrandDNA = {
  id: 'dna-1',
  workspace_id: 'demo-ws-1',
  step1_brand_name: 'Nexum360',
  step1_tagline: 'Estratégia que transforma',
  step1_offerings: 'Consultoria estratégica de marca, gestão de conteúdo com IA e operação de growth para PMEs e marcas pessoais.',
  step1_logo_url: null,
  step1_mission: 'Ajudar empresas a crescerem com estratégia digital inteligente e conteúdo de impacto.',
  step1_vision: 'Ser a principal referência em marketing estratégico para pequenas e médias empresas no Brasil.',
  step1_values: ['Estratégia', 'Transparência', 'Resultado', 'Inovação'],
  step2_profile: 'B2B',
  step2_maturity: 'intermediario',
  step2_roles: ['Gestores', 'Empresários', 'Empreendedores'],
  step2_pain_points: ['Falta de tempo', 'Não saber por onde começar', 'Conteúdo sem estratégia', 'Baixo engajamento'],
  step2_consumption_context: 'Profissional no escritório pesquisando soluções entre reuniões, ou empreendedor no celular à noite buscando referência rápida.',
  step2_attention_triggers: 'Dados de mercado, cases com resultados reais, provocações sobre erros comuns do setor.',
  step2_target_audience: 'Gestores e empreendedores de PMEs que querem crescer digitalmente mas não têm tempo ou conhecimento para criar conteúdo estratégico.',
  step2_age_range: '28-45 anos',
  step2_interests: ['Marketing digital', 'Crescimento de negócios', 'Liderança', 'Tecnologia'],
  step2_persona_name: null,
  step3_tone: ['inspirador', 'educativo', 'direto'],
  step3_personality_traits: ['Confiante', 'Acessível', 'Especialista', 'Pragmático'],
  step3_avoid_words: ['obviamente', 'simplesmente', 'revolucionário', 'disruptivo'],
  step3_preferred_words: ['estratégia', 'resultado', 'crescimento', 'impacto', 'inteligente'],
  step4_primary_colors: ['#6366f1', '#1e1b4b', '#ffffff'],
  step4_typography_style: 'moderno-minimalista',
  step4_visual_references: ['HubSpot', 'Rock Content', 'Neil Patel'],
  step4_aesthetic_keywords: ['limpo', 'profissional', 'moderno', 'confiável'],
  step5_differentiators: 'Unimos estratégia de dados com criatividade humana e IA para produzir conteúdo que gera resultado real, não apenas engajamento.',
  step5_competitors: ['Agências tradicionais', 'Freelancers', 'Ferramentas de IA genéricas'],
  step5_market_position: 'especialista',
  step5_content_pillars: ['Estratégia', 'Cases', 'Educação', 'Bastidores', 'Tendências'],
  current_step: 5,
  completed: true,
  completed_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}
